"""P0 upgrade tests: canonical trim-and-fill, REML/PM τ², HKSJ CI, PI, LOO.

Golden-data provenance: yi/vi vectors generated by R metafor 5.0-1
(trimfill on rma.uni DL), seeds 99 / 4242, captured 2026-08-14.
Golden expectations = metafor's own k0 and pooled estimates on those vectors.
"""

import sys
from pathlib import Path
from typing import ClassVar

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from _stats import (
    heterogeneity,
    leave_one_out,
    pool_random,
    pool_random_advanced,
    tau_squared_paule_mandel,
    tau_squared_reml,
    trim_and_fill,
)

# R metafor seed 99 null draw (metafor k0 = 1)
GOLDEN_NULL_YI = [
    0.397212,
    0.607609,
    0.247965,
    0.314380,
    0.528610,
    0.444010,
    0.775336,
    0.846103,
    0.491419,
    0.702715,
    0.852994,
    0.455584,
    0.325522,
    0.759435,
    1.113715,
    0.801732,
    0.523874,
    0.466721,
    0.434817,
    0.587136,
    0.656913,
    0.658508,
    0.846910,
    0.592422,
    0.425590,
]
GOLDEN_NULL_VI = [
    0.071246,
    0.014468,
    0.090206,
    0.164309,
    0.062686,
    0.157188,
    0.087625,
    0.029840,
    0.037175,
    0.018801,
    0.065006,
    0.057887,
    0.020287,
    0.080883,
    0.090924,
    0.081513,
    0.037116,
    0.013780,
    0.013494,
    0.019398,
    0.023239,
    0.012513,
    0.120351,
    0.072392,
    0.109240,
]
# R metafor seed 4242 suppressed draw (metafor k0 = 0, pooled 0.6647125)
GOLDEN_SUPP_YI = [
    0.647005,
    0.964370,
    0.482209,
    0.612756,
    0.473842,
    0.440041,
    0.453909,
    0.632357,
    0.748257,
    0.749340,
    0.948471,
    0.597173,
    0.644023,
    1.387052,
    0.449554,
    0.969415,
    0.366206,
]
GOLDEN_SUPP_VI = [
    0.039481,
    0.090684,
    0.097602,
    0.152188,
    0.021885,
    0.089310,
    0.139202,
    0.021434,
    0.013426,
    0.117583,
    0.096590,
    0.049213,
    0.016411,
    0.082347,
    0.037902,
    0.049843,
    0.105137,
]


class TestTrimAndFillGolden:
    def test_golden_null_matches_metafor_k0(self):
        tf = trim_and_fill(GOLDEN_NULL_YI, GOLDEN_NULL_VI)
        assert tf["n_filled"] == 1  # metafor k0 = 1
        assert tf["estimator"] == "L0"

    def test_golden_null_adjusted_direction(self):
        tf = trim_and_fill(GOLDEN_NULL_YI, GOLDEN_NULL_VI)
        # fill mirrors the largest study to the left → adjusted ≤ original
        assert tf["adjusted_effect"] <= tf["original_effect"] + 1e-12

    def test_golden_suppressed_matches_metafor_k0_and_pooled(self):
        tf = trim_and_fill(GOLDEN_SUPP_YI, GOLDEN_SUPP_VI)
        assert tf["n_filled"] == 0  # metafor k0 = 0
        assert tf["original_effect"] == pytest.approx(0.664712, abs=1e-5)

    def test_too_few_studies(self):
        tf = trim_and_fill([0.5, 0.6], [0.05, 0.05])
        assert tf["n_filled"] == 0
        assert tf["adjusted_effect"] is None

    def test_symmetric_constant_funnel_zero_fill(self):
        eff = [0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65]
        var = [0.05] * 7
        tf = trim_and_fill(eff, var)
        assert tf["n_filled"] == 0


class TestTau2Estimators:
    HET_EFF: ClassVar[list[float]] = [0.2, 0.8, 0.5, 1.1, -0.1, 0.6]
    HET_VAR: ClassVar[list[float]] = [0.08, 0.09, 0.07, 0.12, 0.10, 0.08]

    def test_reml_pm_match_metafor_golden(self):
        # R metafor 5.0-1: rma(method="REML") τ²=0.06346926, method="PM") τ²=0.07828908
        # PM tolerance 5e-5: metafor's own iterative solver stops at ~1e-5;
        # our bisection (tol 1e-10) is the tighter root of the same equation.
        t_reml, c1 = tau_squared_reml(self.HET_EFF, self.HET_VAR)
        t_pm, c2 = tau_squared_paule_mandel(self.HET_EFF, self.HET_VAR)
        assert c1 and c2
        assert t_reml == pytest.approx(0.0634693, abs=1e-5)
        assert t_pm == pytest.approx(0.0782891, abs=5e-5)

    def test_homogeneous_data_zero_tau(self):
        eff = [0.5, 0.52, 0.49, 0.51]
        var = [0.05] * 4
        t, c = tau_squared_reml(eff, var)
        assert t == 0.0
        assert c

    def test_dl_positive_on_heterogeneous(self):
        assert heterogeneity(self.HET_EFF, self.HET_VAR).tau_squared > 0

    def test_invalid_method_raises(self):
        from _stats import _tau2_by_method

        with pytest.raises(ValueError, match="unknown tau"):
            _tau2_by_method([1.0, 2.0], [1.0, 1.0], "bogus")


class TestPoolRandomAdvanced:
    def test_hksj_default_and_wider_than_z(self):
        eff, var = TestTau2Estimators.HET_EFF, TestTau2Estimators.HET_VAR
        p_adv = pool_random_advanced(eff, var)
        p_z = pool_random(eff, var)
        assert p_adv.ci_method == "hksj"
        assert p_adv.tau2_method == "reml"
        assert (p_adv.ci_upper - p_adv.ci_lower) > (p_z.ci_upper - p_z.ci_lower)

    def test_no_hksj_falls_back_to_z(self):
        p = pool_random_advanced([0.2, 0.8, 0.5], [0.09, 0.09, 0.09], hksj=False)
        assert p.ci_method == "z"

    def test_prediction_interval_wider_than_ci(self):
        p = pool_random_advanced(TestTau2Estimators.HET_EFF, TestTau2Estimators.HET_VAR)
        assert p.pi_lower is not None
        assert (p.pi_upper - p.pi_lower) > (p.ci_upper - p.ci_lower)
        assert p.pi_lower < p.ci_lower < p.effect < p.ci_upper < p.pi_upper

    def test_hksj_se_matches_manual_formula(self):
        # hand-computed HKSJ SE from the estimator's own τ² (formula docstring)
        import math

        import numpy as np

        y = np.array([1.0, 2.0, 3.0, 4.0])
        v = np.array([1.0, 1.0, 1.0, 1.0])
        pe = pool_random_advanced([1.0, 2.0, 3.0, 4.0], [1.0, 1.0, 1.0, 1.0])
        w = 1.0 / (v + pe.tau_squared)
        theta = (w * y).sum() / w.sum()
        se_manual = math.sqrt((w * (y - theta) ** 2).sum() / ((len(y) - 1) * w.sum()))
        assert pe.se == pytest.approx(se_manual, rel=1e-9)


class TestLeaveOneOut:
    def test_rows_and_ordering(self):
        eff = TestTau2Estimators.HET_EFF
        var = TestTau2Estimators.HET_VAR
        rows = leave_one_out(eff, var)
        assert len(rows) == 6
        shifts = [abs(r["shift"]) for r in rows]
        assert shifts == sorted(shifts, reverse=True)

    def test_influence_of_outlier_is_largest(self):
        eff = [0.5, 0.52, 0.49, 0.51, 3.0]  # last = outlier
        var = [0.05] * 5
        rows = leave_one_out(eff, var)
        assert rows[0]["omit_index"] == 4
