"""Jurgens 2018 citation-frame lexicons — ported from Allen AI SciCite.

Source: Jurgens et al. (2018). Measuring the Evolution of a Scientific
Field through Citation Frames. TACL, 6, 391-406.
Repository: https://github.com/allenai/scicite

These lexicons are the rule-based features used by SciCite for citation
intent classification. We port the stance-relevant subset (423 terms
across 20 categories) for CPU-only classification without torch/BERT.
"""

from __future__ import annotations

CONTRAST_ACTIONS: list[str] = [
    "be different from",
    "be distinct from",
    "clash",
    "conflict",
    "contrast",
    "differ from",
    "differentiate",
    "disagree",
    "disagreeing",
    "dissent",
    "distinguish",
    "oppose",
]

CONTRAST_NOUNS: list[str] = [
    "clash",
    "clashes",
    "conflict",
    "contrast",
    "difference",
    "point of departure",
]

CONTRAST_ADJ: list[str] = [
    "competing",
    "contrary",
    "different",
    "distinguishing",
    "rival",
]

CONTRAST_ADV: list[str] = [
    "contrarily",
    "contrastingly",
    "differently",
    "distinguishingly",
    "imcompatibly",
    "on the other hand",
    "other than",
    "otherwise",
]

DISCOURSE_CONTRAST: list[str] = [
    "however",
    "unfortunately",
    "whereas",
]

BAD_ADJ: list[str] = [
    "NP complete",
    "NP hard",
    "NP-complete",
    "NP-hard",
    "absent",
    "ad hoc",
    "ad-hoc",
    "adhoc",
    "ambiguous",
    "annoying",
    "arbitrary",
    "awkward",
    "bad",
    "brittle",
    "brute force",
    "brute-force",
    "careless",
    "confounding",
    "contradictory",
    "defect",
    "defunct",
    "disturbing",
    "elusive",
    "erraneous",
    "expensive",
    "exponential",
    "fallacious",
    "false",
    "frustrating",
    "haphazard",
    "ill-defined",
    "imperfect",
    "implausible",
    "impossible",
    "impractical",
    "imprecise",
    "improper",
    "inaccurate",
    "inadequate",
    "inappropriate",
    "incomplete",
    "incomprehensible",
    "inconclusive",
    "incorrect",
    "inefficient",
    "inelegant",
    "inexact",
    "infeasible",
    "infelicitous",
    "inflexible",
    "inpracticable",
    "insufficient",
    "intractable",
    "invalid",
    "irrelevant",
    "labor intensive",
    "laborintensive",
    "laborious",
    "labour intensive",
    "labour-intensive",
    "limited",
    "limited coverage",
    "limited-coverage",
    "limiting",
    "meaningless",
    "misguided",
    "misleading",
    "modest",
    "nonexistent",
    "only",
    "overly",
    "pathological",
    "poor",
    "prone",
    "protracted",
    "questionable",
    "restricted",
    "scarce",
    "simplistic",
    "suspect",
    "time consuming",
    "time-consuming",
    "too",
    "toy",
    "unacceptable",
    "unaccounted",
    "unaccounted for",
    "unaccounted-for",
    "unattractive",
    "unavailable",
    "unavoidable",
    "unclear",
    "uncomfortable",
    "undecidable",
    "undesirable",
    "unexplained",
    "unfortunate",
    "uninnovative",
    "uninterpretable",
    "unjustified",
    "unmotivated",
    "unnatural",
    "unnecessary",
    "unorthodox",
    "unpleasant",
    "unpractical",
    "unprincipled",
    "unreliable",
    "unsatisfactory",
    "unsound",
    "unsuccessful",
    "unsuited",
    "unsystematic",
    "untractable",
    "unwanted",
    "unwelcome",
    "useless",
    "vulnerable",
    "weak",
    "wrong",
]

AGREE_ACTIONS: list[str] = [
    "agree with",
    "side with",
]

CONTINUE_ACTIONS: list[str] = [
    "adopt",
    "base",
    "base on",
    "be base on",
    "borrow",
    "build on",
    "derive from",
    "follow",
    "following",
    "originate from",
    "originate in",
    "proceed from",
    "start from",
]

SIMILAR_ADJ: list[str] = [
    "analogous",
    "comparable",
    "kindred",
    "similar",
]

GOOD_ADJ: list[str] = [
    "adequate",
    "advantageous",
    "appealing",
    "appropriate",
    "attractive",
    "automatic",
    "beneficial",
    "capable",
    "cheerful",
    "clean",
    "clear",
    "compact",
    "compelling",
    "competitive",
    "comprehensive",
    "consistent",
    "constructive",
    "convenient",
    "convincing",
    "correct",
    "desirable",
    "distinctive",
    "effective",
    "efficient",
    "elegant",
    "encouraging",
    "enough",
    "exact",
    "faultless",
    "favourable",
    "feasible",
    "flawless",
    "good",
    "helpful",
    "impeccable",
    "innovative",
    "insightful",
    "intensive",
    "meaningful",
    "neat",
    "perfect",
    "plausible",
    "polynomial",
    "positive",
    "powerful",
    "practical",
    "precise",
    "preferable",
    "principled",
    "promising",
    "pure",
    "realistic",
    "reasonable",
    "reliable",
    "right",
    "robust",
    "satisfactory",
    "simple",
    "sound",
    "successful",
    "sufficient",
    "systematic",
    "tractable",
    "unlimited",
    "usable",
    "useful",
    "valid",
    "well",
    "well worked out",
    "well-motivated",
]

COMPARISON_NOUNS: list[str] = [
    "accuracy",
    "baseline",
    "comparison",
    "competition",
    "evaluation",
    "inferiority",
    "measure",
    "measurement",
    "optimum",
    "performance",
    "precision",
    "recall",
    "superiority",
]

USE_ACTIONS: list[str] = [
    "apply",
    "employ",
    "implement",
    "make use",
    "resort to",
    "use",
    "utilize",
]

WORK_NOUNS: list[str] = [
    "account",
    "algorithm",
    "analyses",
    "analysis",
    "application",
    "approach",
    "approaches",
    "architecture",
    "characterisation",
    "characterization",
    "component",
    "design",
    "extension",
    "formalisation",
    "formalism",
    "formalization",
    "framework",
    "implementation",
    "investigation",
    "machinery",
    "method",
    "methodology",
    "model",
    "module",
    "moduls",
    "procedure",
    "process",
    "program",
    "prototype",
    "research",
    "researches",
    "strategy",
    "system",
    "technique",
    "theory",
    "tool",
    "treatment",
    "work",
]

PRESENTATION_ACTIONS: list[str] = [
    "describe",
    "discuss",
    "give",
    "introduce",
    "note",
    "notice",
    "point out",
    "present",
    "propose",
    "put forward",
    "recapitulate",
    "remark",
    "report",
    "say",
    "show",
    "sketch",
    "state",
    "suggest",
    "talk about",
]

NEGATION: list[str] = [
    "aren't",
    "can't",
    "cannot",
    "didn't",
    "doesn't",
    "don't",
    "few",
    "hadn't",
    "hardly",
    "hasn't",
    "haven't",
    "isn't",
    "least",
    "less",
    "little",
    "n't",
    "neither",
    "never",
    "no",
    "nobody",
    "non",
    "none",
    "nor",
    "not",
    "nothing",
    "rare",
    "rarely",
    "scant",
    "scarcely",
    "unlikely",
    "wasn't",
    "weren't",
]

HEDGING: list[str] = [
    "could",
    "may",
    "might",
    "should",
]

DOWNTONERS: list[str] = [
    "almost",
    "barely",
    "hardly",
    "merely",
    "mildly",
    "nearly",
    "only",
    "partially",
    "partly",
    "practically",
    "scarcely",
    "slightly",
    "somewhat",
]

ARGUMENTATION_NOUNS: list[str] = [
    "assumption",
    "belief",
    "claim",
    "conclusion",
    "confirmation",
    "hypotheses",
    "hypothesis",
    "opinion",
    "recommendation",
    "stipulation",
    "view",
]

BEFORE_ADJ: list[str] = [
    "earlier",
    "initial",
    "past",
    "previous",
    "prior",
]

TRADITION_ADJ: list[str] = [
    "available",
    "better known",
    "better-known",
    "cited",
    "classic",
    "common",
    "conventional",
    "current",
    "customary",
    "established",
    "existing",
    "extant",
    "fashionable",
    "favourite",
    "general",
    "long-standing",
    "mainstream",
    "modern",
    "naive",
    "obvious",
    "orthodox",
    "popular",
    "prevailing",
    "prevalent",
    "published",
    "quoted",
    "seminal",
    "standard",
    "textbook",
    "traditional",
    "trivial",
    "typical",
    "unanimous",
    "usual",
    "well-established",
    "well-known",
    "widelyassumed",
]

# Grouped for stance classification
CONTRAST_TERMS = set(CONTRAST_ACTIONS + CONTRAST_NOUNS + CONTRAST_ADJ + CONTRAST_ADV + DISCOURSE_CONTRAST)
SUPPORT_TERMS = set(AGREE_ACTIONS + CONTINUE_ACTIONS + SIMILAR_ADJ + GOOD_ADJ + COMPARISON_NOUNS)
METHOD_TERMS = set(USE_ACTIONS + WORK_NOUNS)
MENTION_TERMS = set(PRESENTATION_ACTIONS + TRADITION_ADJ + BEFORE_ADJ)
NEGATION_TERMS = set(NEGATION + DOWNTONERS)
